org: sanjaym0512
app: emp-backend
service: emp-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
  healthCheck:
    handler: index.healthCheck
    events:
      - httpApi:
          path: healthCheck
          method: get
plugins:
  - serverless-offline